---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: ubuntu-jammy
    box: bento/ubuntu-22.04
    memory: 1024
    cpus: 1
  - name: ubuntu-noble
    box: bento/ubuntu-24.04
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: testinfra
